"""State Vault 儲存後端 Protocol。公開類名仍是 StateVault / TraceLog。"""

from __future__ import annotations

from typing import Protocol

from narratron.vault.schema import Asset, Entity, Shot, TraceRecord


class VaultStore(Protocol):
    def upsert_entities(self, entities: list[Entity]) -> None: ...

    def upsert_shots(self, shots: list[Shot]) -> None: ...

    def upsert_assets(self, assets: list[Asset]) -> None: ...

    def append_traces(self, records: list[TraceRecord]) -> None: ...

    def get_entities(self) -> list[Entity]: ...

    def get_entity(self, entity_id: str) -> Entity | None: ...

    def delete_entity(self, entity_id: str) -> None: ...

    def get_shots(self) -> list[Shot]: ...

    def get_assets(self) -> list[Asset]: ...

    def get_traces(self) -> list[TraceRecord]: ...

    def list_traces_for_entity(self, entity_id: str) -> list[TraceRecord]: ...

    def list_traces_for_shot(self, shot_id: str) -> list[TraceRecord]: ...
